language: python

# To automatically push to anaconda cloud tag a relase in the git repository
# git tag -a v0.2.3 -m 'This version has the new cool features X, Y, Z'
# git push --tags



jobs:
  include:
    - name: "linux"
      os: linux
      language: python
      python: 3.7           # this works for Linux but is ignored on macOS or Windows
      before_install:
        # To make sure travis can read the GIT_DESCRIBE_TAG properly we need to force an unshallow fetch
        - git fetch --unshallow
        # Install the latest version of Miniconda
        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
        - chmod +x miniconda.sh
        - ./miniconda.sh -b
        - pwd
        - export PATH=/home/travis/miniconda3/bin:$PATH
        - conda update --yes conda  # Update CONDA without command line prompt     
      env:
        - CC=gcc-5
        - CXX=g++-5
#    - name: "osx"
#      os: osx
#      language: sh
#      before_cache:
#        - brew cleanup
#      cache:
#        directories:
#          - $HOME/Library/Caches/Homebrew
#          - /usr/local/Homebrew
#      addons:
#        homebrew:
#          packages: python3
#      before_install:
#        # To make sure travis can read the GIT_DESCRIBE_TAG properly we need to force an unshallow fetch
#        - git fetch --unshallow
#        # Install the latest version of Miniconda
#        - wget http://repo.continuum.io/miniconda/Miniconda3-latest-MacOSX-x86_64.sh -O miniconda.sh
#        - chmod +x miniconda.sh
#        - ./miniconda.sh -b
#        - pwd
#        - export PATH=/Users/travis/miniconda3/bin:$PATH
#        - conda update --yes conda  # Update CONDA without command line prompt 
#      env:
#        - CC=clang
#        - CXX=clang++



install:
  - which python
  - pip wheel . --index-url https://test.pypi.org/simple --extra-index-url https://pypi.org/simple -w dist
  - pip install --index-url https://test.pypi.org/simple --extra-index-url https://pypi.org/simple dist/easyreg*
 

# command to install dependencies
#install:
#  - python setup.py install

# command to run tests
script: ./travis_test.sh

after_success:
  # Install the command line API for CONDA uploads
  - conda install --yes anaconda-client
  - |
    ## Only upload builds from tags
    if [[ $TRAVIS_PULL_REQUEST == false && $TRAVIS_REPO_SLUG == "uncbiag/easyreg" && $TRAVIS_BRANCH == $TRAVIS_TAG  && $TRAVIS_TAG != '' ]]; then
      export ANACONDA_API_TOKEN=$CONDA_UPLOAD_TOKEN
      anaconda upload --user uncbiag bld-dir/**/easyreg-*.tar.bz2
    fi
